#!/usr/bin/env node
/**
 * Copies the compiled ABI of every v2 core contract out of the Foundry artifact
 * directory (`out/<C>.sol/<C>.json`) into `src/abis/<C>.ts` as a typed const so
 * viem can infer argument and return types from it.
 *
 * Usage: npm run abi:sync   (run `forge build` in the repo root first)
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const CONTRACTS = [
  'AgentAccess',
  'AgentIdentityV2',
  'AgentReputationV2',
  'AgentKillSwitchV2',
  'AgentAuditLogV2',
  'FeeRouter',
  'AgentEscrowV2',
];

const here = dirname(fileURLToPath(import.meta.url));
const sdkRoot = resolve(here, '..');
const repoRoot = resolve(sdkRoot, '..', '..');
const outDir = join(repoRoot, 'out');
const abiDir = join(sdkRoot, 'src', 'abis');

function readAbi(contract) {
  const artifact = join(outDir, `${contract}.sol`, `${contract}.json`);
  let raw;
  try {
    raw = readFileSync(artifact, 'utf8');
  } catch (error) {
    throw new Error(
      `Missing artifact ${artifact}. Run \`forge build\` in ${repoRoot} first. (${error.message})`,
    );
  }
  const parsed = JSON.parse(raw);
  if (!Array.isArray(parsed.abi) || parsed.abi.length === 0) {
    throw new Error(`Artifact ${artifact} has no abi entries`);
  }
  return parsed.abi;
}

function render(contract, abi) {
  return [
    '// Generated by scripts/sync-abis.mjs — do not edit by hand.',
    `// Source: out/${contract}.sol/${contract}.json`,
    `export const ${contract}Abi = ${JSON.stringify(abi, null, 2)} as const;`,
    '',
  ].join('\n');
}

mkdirSync(abiDir, { recursive: true });

const index = [
  '// Generated by scripts/sync-abis.mjs — do not edit by hand.',
];
for (const contract of CONTRACTS) {
  const abi = readAbi(contract);
  writeFileSync(join(abiDir, `${contract}.ts`), render(contract, abi), 'utf8');
  index.push(`export { ${contract}Abi } from './${contract}.js';`);
  process.stdout.write(`synced ${contract} (${abi.length} entries)\n`);
}
index.push("export { erc20Abi } from './erc20.js';", '');
writeFileSync(join(abiDir, 'index.ts'), index.join('\n'), 'utf8');
process.stdout.write(`wrote ${abiDir}/index.ts\n`);
