"""The packaged ABIs are the SDK's contract with the chain, so assert their shape directly.

Every entry here is regenerated by `scripts/sync_abis.py` from a fresh `forge build`; a failure
means the SDK and the deployed contracts have drifted apart, not that a test needs loosening.
"""

from __future__ import annotations

import pytest

from nexusweb3.abi import CONTRACT_NAMES, load_abi


def test_every_abi_is_packaged_and_loadable() -> None:
    for name in CONTRACT_NAMES:
        abi = load_abi(name)
        assert any(entry.get("type") == "function" for entry in abi)
    with pytest.raises(KeyError):
        load_abi("NotAContract")


def _abi_names(contract: str, kind: str) -> set[str]:
    return {entry["name"] for entry in load_abi(contract) if entry["type"] == kind}


def test_escrow_abi_exposes_the_interface_surface() -> None:
    names = _abi_names("AgentEscrowV2", "function")
    assert {"createJob", "createJobWithPermit", "approveMilestone", "submitMilestone"} <= names
    assert {"acceptJob", "settleExpired", "withdrawClaimable"} <= names
    assert {"MAX_REJECTIONS", "MAX_REPUTATION_PER_PAIR", "DISPUTE_GRACE"} <= names
    assert "refundExpired" not in names


def test_withdraw_claimable_takes_an_account_and_a_recipient() -> None:
    entry = next(
        e for e in load_abi("AgentEscrowV2")
        if e["type"] == "function" and e["name"] == "withdrawClaimable"
    )
    assert [arg["name"] for arg in entry["inputs"]] == ["account", "to"]


def test_escrow_abi_declares_the_new_events_and_errors() -> None:
    assert {"JobAccepted", "JobExpired", "ClaimableWithdrawn", "PayoutSettled"} <= _abi_names(
        "AgentEscrowV2", "event"
    )
    assert {
        "NotAccepted",
        "AlreadyAccepted",
        "ReviewWindowClosed",
        "TooManyRejections",
        "TokenAmountMismatch",
    } <= _abi_names("AgentEscrowV2", "error")


def test_every_v2_contract_is_ownable_two_step() -> None:
    for contract in ("AgentEscrowV2", "AgentIdentityV2", "AgentKillSwitchV2", "FeeRouter"):
        assert {"transferOwnership", "acceptOwnership", "pendingOwner"} <= _abi_names(contract, "function")


def test_owned_sub_clients_expose_the_two_step_handover() -> None:
    from nexusweb3.contracts import (
        AccessClient,
        AuditLogClient,
        EscrowClient,
        FeeRouterClient,
        IdentityClient,
        KillSwitchClient,
        Ownable2StepClient,
        ReputationClient,
    )

    owned = (
        EscrowClient,
        IdentityClient,
        KillSwitchClient,
        AuditLogClient,
        ReputationClient,
        FeeRouterClient,
    )
    for cls in owned:
        assert issubclass(cls, Ownable2StepClient)
        assert callable(cls.accept_ownership) and callable(cls.transfer_ownership)
    # AgentAccess has no owner at all: it is a pure registry.
    assert not issubclass(AccessClient, Ownable2StepClient)


def test_sibling_module_changes_are_in_the_abis() -> None:
    assert "registryEpoch" in _abi_names("AgentIdentityV2", "function")
    assert "InvalidERC8004Id" in _abi_names("AgentIdentityV2", "error")
    assert "ReferralCallFailed" in _abi_names("FeeRouter", "event")


def test_payout_settled_carries_the_fields_the_sdk_reads_back() -> None:
    entry = next(
        e for e in load_abi("AgentEscrowV2") if e["type"] == "event" and e["name"] == "PayoutSettled"
    )
    assert [arg["name"] for arg in entry["inputs"]] == ["jobId", "account", "amount", "delivered"]
    assert [arg["type"] for arg in entry["inputs"]] == ["uint256", "address", "uint256", "bool"]


def test_identity_abi_exposes_rename_and_its_event() -> None:
    entry = next(
        e for e in load_abi("AgentIdentityV2") if e["type"] == "function" and e["name"] == "rename"
    )
    assert [arg["name"] for arg in entry["inputs"]] == ["agent", "newName"]
    assert "AgentRenamed" in _abi_names("AgentIdentityV2", "event")


def test_sdk_wraps_every_new_contract_call() -> None:
    from nexusweb3.contracts import EscrowClient, IdentityClient

    assert callable(IdentityClient.rename)
    assert callable(EscrowClient._with_payouts)
